import type { Metadata } from 'next';
import ComparisonPageTemplate from '@/components/ui/ComparisonPageTemplate';

export const metadata: Metadata = {
    title: 'AiSensy Alternative in India | D2C Retargeting & AI Helpdesk',
    description: 'Stop using basic broadcast tools for customer support. Migrate from AiSensy to SwanDesk for a complete omnichannel AI Helpdesk with native LLM capabilities.',
    keywords: ['AiSensy alternative', 'AiSensy vs SwanDesk', 'WhatsApp Broadcast India', 'D2C Customer Support AI'],
    alternates: {
        canonical: 'https://swandigitals.com/compare/vs-aisensy',
    },
}

export default function VsAiSensyPage() {
    return (
        <ComparisonPageTemplate
            competitorName="AiSensy"
            heroTitle="AiSensy Alternative in India"
            heroSubtitle="AiSensy is great for blasting WhatsApp marketing messages. But when customers reply with complex problems, you need SwanDesk."
            aboutCompetitor="AiSensy is a highly popular WhatsApp marketing platform in India, used extensively by D2C brands and marketing agencies to send broadcast campaigns and retargeting messages."
            competitorStrengths="Excellent campaign management, easy WhatsApp Green Tick approval process, and strong integrations with Shopify and WooCommerce for cart recovery."
            realityCheck="AiSensy is a marketing tool first, and a helpdesk second. When a customer replies to your broadcast with a complex issue (like a broken product or a refund request), AiSensy's basic keyword bots fail. Your human agents are left overwhelmed in a basic inbox that lacks enterprise SLA management, ticketing, and true LLM automation."
            reasonsToSwitch={[
                {
                    title: "Helpdesk First, Marketing Second",
                    description: "SwanDesk is a unified CRM. It handles your marketing broadcasts, but more importantly, it provides an enterprise-grade inbox to resolve the support tickets generated by those broadcasts."
                },
                {
                    title: "Advanced Generative AI",
                    description: "Stop relying on 'if-this-then-that' keyword rules. SwanDesk ingests your entire product catalog and policies to answer complex customer queries automatically."
                },
                {
                    title: "Omnichannel Support",
                    description: "AiSensy limits you to WhatsApp. SwanDesk unifies WhatsApp, Web Chat, Email, and native Voice AI into a single agent view."
                }
            ]}
            comparisonRows={[
                { feature: "Primary Focus", SwanDesk: "AI Support & Helpdesk", competitor: "Broadcast Marketing" },
                { feature: "Channels Supported", SwanDesk: "WhatsApp, Web, Email, Voice", competitor: "WhatsApp Only" },
                { feature: "Generative AI Resolution", SwanDesk: "Native (RAG Architecture)", competitor: "Basic Dialogflow/Keywords" },
                { feature: "Ticketing & SLA", SwanDesk: "Enterprise Grade", competitor: "Basic Inbox" },
                { feature: "Pricing Predictability", SwanDesk: "Flat SaaS Model", competitor: "Tiered / Volume Based" }
            ]}
            targetPersona="You are a D2C brand whose only goal is to recover abandoned carts on Shopify and blast promotional offers, and you handle support manually."
            verdict="You realize that excellent customer support drives more LTV than a marketing blast. You need an AI-first omnichannel platform that can resolve complex tickets automatically while still supporting your marketing needs."
            faqs={[
                {
                    question: "Can I run WhatsApp marketing campaigns on SwanDesk?",
                    answer: "Yes. We support outbound WhatsApp campaigns, but we pair it with an intelligent AI that can handle the massive influx of customer replies automatically."
                }
            ]}
        />
    );
}
